* Deprecate the Anbernic Kernel on the main branch * Update Make World to build 32 and 64bit 351ELEC

diff --git a/scripts/build_distro b/scripts/build_distro
--- a/scripts/build_distro
+++ b/scripts/build_distro
@@ -3,93 +3,35 @@
 # Copyright (C) 2020-present Fewtarius
 
 ###
-### Simple script to build 351ELEC using the Anbernic kernel or the lualiliu kernel.
+### Simple script to build 351ELEC
 ###
+
+if [ !"${ARCH}" == true ]
+then
+  echo "export ARCH before building."
+  exit 1
+fi
 
 export DISTRO=351ELEC
 export PROJECT=Rockchip
 export DEVICE=RG351P
 
-if [ ! "${1^^}" == "WORLD" ] && [ ! "${1^^}" == "RESET" ]
+if [ ! -d "target" ]
 then
-  BUILD=$(echo ${BUILD} | sed 's#^.*-##')
-  BUILD="${DEVICE}-${1^^}"
-else
-  BUILD=$(echo ${1^^})
+  mkdir target
 fi
 
-function RG351P-LI () {
-  echo "Checking out the latest Linux kernel packages for building."
-  echo "Setting build device directory to ${BUILD}"
-  rm -rf projects/Rockchip/devices/RG351P
-  cp -rf projects/Rockchip/devices/RG351P-LI projects/Rockchip/devices/RG351P
-  make $1 || exit 1
-  if [ -d "release/${ARCH}/RG351P-LI" ]
-  then
-    rm -rf "release/${ARCH}/RG351P-LI"
-  fi
-  mv target release/${ARCH}/RG351P-LI
-  mkdir target
-  RESET
-}
-
-function RG351P-AK () {
-  echo "Removing Linux kernel packages for Anbernic injection"
-  rm -rf packages/linux
-  rm -rf packages/linux-driver-addons
-  rm -rf packages/linux-drivers
-  rm -rf packages/linux-firmware
-  rm -rf packages/virtual/linux-drivers
-  rm -rf packages/virtual/linux-firmware
-  rm -rf projects/Rockchip/devices/RG351P
-  cp -rf projects/Rockchip/devices/RG351P-AK projects/Rockchip/devices/RG351P
-  make $1 || exit 1
-  if [ -d "release/${ARCH}/RG351P-AK" ]
-  then
-    rm -rf "release/${ARCH}/RG351P-AK"
-  fi
-  mv target release/${ARCH}/RG351P-AK
-  mkdir target
-  RESET
-}
-
-function RESET () {
-  #git checkout projects/Rockchip/options
-  git checkout packages/linux
-  git checkout packages/linux-driver-addons
-  git checkout packages/linux-drivers
-  git checkout packages/linux-firmware
-  git checkout packages/virtual/linux-drivers
-  git checkout packages/virtual/linux-firmware
-}
-
-for dir in release target
-do
-  if [ ! -d "${dir}" ]
-  then
-    mkdir ${dir}
-  fi
-done
-
-RESET
-mkdir release/${ARCH} 2>/dev/null
-
-if [ "${BUILD}" == "RG351P-LI" ]
+if [ -d "release/${ARCH}/RG351P" ]
 then
-  RG351P-LI image
-elif [ "${BUILD}" == "RG351P-AK" ]
+  rm -rf "release/${ARCH}/RG351P"
+fi
+mkdir -p release/${ARCH}/RG351P
+
+make image
+if [ ! $? == 0 ]
 then
-  RG351P-AK image
-elif [ "${BUILD}" == "WORLD" ]
-then
-  # Temporary build world loop, replace with a virtual package.
-  RG351P-LI image
-  RG351P-AK image
-elif [ "${BUILD}" == "RESET" ]
-then
-  RESET
-else
-  echo "Pass the project to build (LI,AK,WORLD) as an argument on the command line. [${BUILD}]"
+  echo "Build failed..exiting."
   exit 1
 fi
 
+cp -rf "target/*" "release/${ARCH}/RG351P/"
